### ISSUE TITLE
Missing support of String Expressions for Raster

### ISSUE THREAD

**Issue by frodrigo** [maptiler/tileserver-gl#298]
Using String Expression for "text-field" in GL style works with vector tiles but does not works with the raster tiles output.
Event simplest string expressions does not work.

```json
    {
      "id": "country_label",
      "type": "symbol",
      "source": "openmaptiles",
      "source-layer": "place",
      "maxzoom": 12,
      "filter": [
        "all",
        [
          "==",
          "$type",
          "Point"
        ],
        [
          "==",
          "class",
          "country"
        ],
        [
          "has",
          "iso_a2"
        ]
      ],
      "layout": {
        "text-field": [  <----------------------------------
          "get",
          "name"
        ],
        "text-font": [
          "Noto Sans Bold"
        ],
```

Raster output
![image](https://user-images.githubusercontent.com/1785486/42645202-c45d4eb8-85fd-11e8-99aa-1e50eda31f90.png)

Vector output
![image](https://user-images.githubusercontent.com/1785486/42645219-d18113ea-85fd-11e8-826a-9ac13c0272f8.png)

Version of the TileServer GL : Docker lastest/v2.3.1.

My goal is to override the default language on raster tiles using:
```json
        "text-field": [                                                                                                                     
          "coalesce",                                                                                                                       
          [                                                                                                                                 
            "get",                                                                                                                          
            "name:he"                                                                                                                       
          ],                                                                                                                                
          [                                                                                                                                 
            "get",                                                                                                                          
            "name"                                                                                                                          
          ]                                                                                                                                 
        ],   
```

**Comment by nishanthdn96** [comment]
@frodrigo  Any update on this? I'm also facing the same issue

**Comment by frodrigo** [comment]
I did not look further at it, but still need it.

**Comment by petrsloup** [comment]
This should be solved in v3.0.0 (maybe even sooner), since we upgraded to much newer version of mapbox-gl-native with support for expressions.

**Comment by nishanthdn96** [comment]
@petrsloup I'm still facing this issue.
I'm using the latest version.
docker version **maptiler/tileserver-gl:v3.0.0**
mapbox styling:
```
"layers": [
    {
      "id": "5ebb6e6e0d45ca69977eb538",
      "type": "symbol",
      "source": "5e95cdb424c827163382e456",
      "paint": {
        "text-color": [
          "step",
          [
            "zoom"
          ],
          "#000000",
          0,
          "#000000"
        ],
        "text-opacity": [
          "step",
          [
            "zoom"
          ],
          1,
          0,
          1
        ],
        "icon-color": [
          "step",
          [
            "zoom"
          ],
          "#770008",
          0,
          "#770008"
        ],
        "icon-opacity": [
          "step",
          [
            "zoom"
          ],
          1,
          0,
          1
        ]
      },
      "layout": {
        "visibility": "visible",
        "text-offset": [
          0,
          1.5
        ],
        "text-field": [
          "to-string",
          [
            "get",
            "LOCALITY"
          ]
        ],
        "text-size": [
          "interpolate",
          [
            "linear"
          ],
          [
            "zoom"
          ],
          0,
          10
        ],
        "text-transform": [
          "step",
          [
            "zoom"
          ],
          "none",
          0,
          "none"
        ],
        "icon-image": [
          "step",
          [
            "zoom"
          ],
          "bus",
          0,
          "bus"
        ],
        "icon-size": [
          "step",
          [
            "zoom"
          ],
          1,
          0,
          1
        ],
        "text-font": [
          "step",
          [
            "zoom"
          ],
          [
            "literal",
            [
              "Open Sans Regular",
              "Open Sans Regular"
            ]
          ],
          0,
          [
            "literal",
            [
              "Open Sans Regular",
              "Open Sans Regular"
            ]
          ]
        ],
        "text-letter-spacing": [
          "interpolate",
          [
            "linear"
          ],
          [
            "zoom"
          ],
          0,
          0.0625
        ],
        "text-justify": [
          "step",
          [
            "zoom"
          ],
          "left",
          0,
          "left"
        ]
      },
      "maxzoom": 22,
      "minzoom": 1,
      "source-layer": "5e95cdb424c827163382e456"
    }
  ]
```
**Raster output:**
<img width="1008" alt="Screenshot 2020-05-13 at 9 22 09 AM" src="https://user-images.githubusercontent.com/51163080/81769832-3203ca00-94fc-11ea-9601-b5094df36402.png">
**Vector output**
<img width="1008" alt="Screenshot 2020-05-13 at 9 22 52 AM" src="https://user-images.githubusercontent.com/51163080/81769839-36c87e00-94fc-11ea-8731-8d2d297de877.png">

**Comment by frodrigo** [comment]
As I see you use the old style, not expression.
